services:

  nats:
    image: 'nats:2.10.20'
    networks:
      - 'public'
    ports:
      - '4222:4222/tcp'

  sqlite-web:
    image: 'coleifer/sqlite-web:latest'
    environment:
      SQLITE_DATABASE: 'data.sqlite'
    volumes:
      - './data.sqlite:/data/data.sqlite'
    networks:
      - 'public'
    ports:
      - '8081:8080/tcp'

networks:

  public:
    name: 'public'
